/**************************************************************************************************
 * File name    : AppDelegate.h
 * Description  : Define the class AppDelegate, which is automatically generated by Mac OS Cocoa project template
 * Creator      : Frederick Hsu
 * Creation date: Mon.  06 March 2017
 * Copyright(C) 2017    All rights reserved.
 *
 **************************************************************************************************/

#import <Cocoa/Cocoa.h>

@interface AppDelegate : NSObject <NSApplicationDelegate>

    @property (nonatomic, strong) NSWindow *myWindow;

    - (NSWindow *)showMyWindow;

    - (void)setWindowIcon;
    - (void)setWindowBackgroundColor;

    - (void)recvWindowWillCloseMesg:(NSNotification *)notification;

    - (void)addButtonToTitleBar;
    - (void)setWindowDisplayPosition;

@end
